name = "ebola-birthdays"
main = "src/worker.ts"
compatibility_date = "2023-05-15"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["30 13 * * *"]

[vars]
SHITTY_API_URL = 'https://shitty-api.fly.dev'
BOTNORREA_WEBHOOK = 'https://59lbo0f12c.execute-api.us-east-2.amazonaws.com/prod/publicWebhook'
SENTRY_DSN = "https://371452aee255bb54d46c2ad05e2ec94b@o4505665165197312.ingest.sentry.io/4505665202225152"
STAGE = 'production'
SENTRY_ORG = 'crappy-corp'
SENTRY_PROJECT = 'shitty-workers'
